#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXP0R6oA3/q7xeX++rjsZCR4mw69KZZQcDWamS8Aj+/gMO5xx7QZvf/3RYhDF/QZNix0GSG80x2KRZnwbTo/wnFp06BEeRYU3FHGOrS33O5Z4hn5THXUeiZdCUMQxeK03Lj+ajFHile20Eqx23RZwCkKWPY2hrneehLR02o1n8l1kSSxrKozLRge+uPrV1IVBszqZDcyXQ7KK5N3N/nmNnb81chZH8UGT0MlJbqKL90v+LdliVtwT9hKK2C0v3bHgDo+rPImEVMzXg85+kso88paZKntlvXSAbg9KfKHHKms/iykOhsnURPb99S/uR4Q8wUQd6piwBGcMR2hQ1P8KB allan@adegnan.net
coreos:
  units:
    - name: fleet.service
      command: stop
      enable: false
    - name: etcd.service
      command: stop
      enable: false
    - name: etcd2.service
      command: stop
      enable: false
    - name: flanneld.service
      command: start
      enable: true
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.10.0.0/16","Backend":{"Type":"vxlan"}}'
    - name: install-kubernetes.service
      command: start
      content: |
        [Unit]
        Description=Install kubernetes

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        TimeoutStartSec=300
        Environment="URL=https://storage.googleapis.com/kubernetes-release/release/v1.1.7/bin/linux/amd64/hyperkube"
        Environment="OUTPUT_FILE=/opt/bin/hyperkube"
        Environment="MD5SUM=dd57058362afce77a94ba4e9152a4525"
        ExecStart=/usr/bin/mkdir -p /opt/bin
        ExecStart=/usr/bin/curl --silent -o ${OUTPUT_FILE} ${URL}
        ExecStart=/usr/bin/md5sum ${OUTPUT_FILE}
        ExecStart=/usr/bin/chmod +x ${OUTPUT_FILE}

    - name: kube-kubelet.service
      command: start
      enable: true
      content: |
        [Unit]
        Description=Kubernetes Kubelet
        Documentation=https://github.com/kubernetes/kubernetes

        [Service]
        Environment="URL=http://nas.lan/manifests"
        Environment="SRC_PATH=/srv/kubernetes/manifests"
        Environment="DST_PATH=/etc/kubernetes/manifests"
        ExecStartPre=/usr/bin/rm -rf /etc/kubernetes/manifests
        ExecStartPre=/usr/bin/rm -rf /srv/kubernetes/manifests
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/usr/bin/mkdir -p /srv/kubernetes/manifests

        ExecStartPre=/usr/bin/env bash -c 'curl --silent -H remote-hostname:$(hostname) -o ${DST_PATH}/kube-apiserver.yaml http://nas.lan/manifests/api/kube-apiserver.yaml'
        ExecStartPre=/usr/bin/env bash -c 'curl --silent -H remote-hostname:$(hostname) -o ${DST_PATH}/kube-etcd.yaml ${URL}/api/kube-etcd.yaml'
        ExecStartPre=/usr/bin/env bash -c 'curl --silent -H remote-hostname:$(hostname) -o ${DST_PATH}/kube-apiserver.yaml ${URL}/api/kube-apiserver.yaml'
        ExecStartPre=/usr/bin/env bash -c 'curl --silent -H remote-hostname:$(hostname) -o ${DST_PATH}/kube-podmaster.yaml ${URL}/api/kube-podmaster.yaml'
        ExecStartPre=/usr/bin/env bash -c 'curl --silent -H remote-hostname:$(hostname) -o ${DST_PATH}/kube-proxy.yaml ${URL}/compute/kube-proxy.yaml'
        ExecStartPre=/usr/bin/env bash -c 'curl --silent -H remote-hostname:$(hostname) -o ${SRC_PATH}/kube-controller-manager.yaml ${URL}/master/kube-controller-manager.yaml'
        ExecStartPre=/usr/bin/env bash -c 'curl --silent -H remote-hostname:$(hostname) -o ${SRC_PATH}/kube-scheduler.yaml ${URL}/master/kube-scheduler.yaml'

        ExecStart=/opt/bin/hyperkube kubelet \
          --api-servers=http://127.0.0.1:8080 \
          --allow-privileged=true \
          --config=/etc/kubernetes/manifests \
          --v=2
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
