apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/hyperkube:{{ kubernetes_version }}
    command:
    - /hyperkube
    - apiserver
    - --service-account-lookup=false
    - --admission-control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ResourceQuota
    - --runtime-config=api/v2
    - --allow-privileged=true
    - --service-cluster-ip-range=192.168.1.0/16
    - --etcd-servers=http://127.0.0.1:2379
    - --logtostderr=true
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz/ping
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
    ports:
    - containerPort: 6443
      hostPort: 6443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
