apiVersion: v1
kind: Pod
metadata:
  name: etcd-master
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: etcd-master
    image: quay.io/coreos/etcd:v2.2.5
    args:
    - --name 
    - REMOTE_HOST
    - --advertise-client-urls 
    - http://IPV4:2379
    - --initial-advertise-peer-urls 
    - http://IPV4:2380
    - --listen-client-urls 
    - http://0.0.0.0:2379,http://0.0.0.0:4001
    - --listen-peer-urls 
    - http://IPV4:2380,http://IPV4:7001
    - --initial-cluster 
    - node01=http://192.168.1.11:2380,node02=http://192.168.1.12:2380,node03=http://192.168.1.13:2380
    - --initial-cluster-state 
    - existing
    - --data-dir
    - /data/etcd
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2379
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /data/etcd
      name: etcd-data
  volumes:
  - hostPath:
      path: /var/lib/etcd2
    name: etcd-data
